## TensorFlow 2.0 低阶API

### tf.constant提供常量的声明

In [1]:
import tensorflow as tf
a = tf.constant(7)
a

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=7>

In [2]:
a.numpy()

7

### tf.Variabke提供变量的声明

In [3]:
a1 = 7
a2 = tf.Variable(7)
a3 = tf.Variable([0,1,2])

a1, a2, a3

(7,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2], dtype=int32)>)

### tf.reshape 提供多阶Tensor的形状变换功能

In [34]:
a = tf.Variable([[0,1,2], [3,4,5]])
print(a.shape)

(2, 3)


In [37]:
a1 = tf.reshape(a, [3,2])
a1

<tf.Tensor: id=128, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5]], dtype=int32)>

### tf.math.reduce_mean提供对Tensor求平均值的功能

In [6]:
a = tf.Variable([1,2., 3, 4, 5, 6, 7.])
print(a.dtype)
print(tf.math.reduce_mean(a))

<dtype: 'float32'>
tf.Tensor(4.0, shape=(), dtype=float32)


In [8]:
b = tf.constant([[1,2,1], [5,5,10]])
print(b.dtype)
print(tf.math.reduce_mean(b))

<dtype: 'int32'>
tf.Tensor(4, shape=(), dtype=int32)


### tf.random.normal 可以随机生成一个Tensor，其值符合正态分布

In [9]:
a = tf.random.normal(shape=[2,3], mean = 2)
print(a.numpy())

[[1.4646244 3.3890672 2.0895777]
 [3.2665656 2.4477305 2.2159247]]


### tf.random.uniform 可以随机生成一个Tensor其值符合均匀分布

In [13]:
a = tf.random.uniform(shape=[2,3], minval = 1, maxval = 10, seed = 8, dtype = tf.int32)
print(a.numpy())

[[4 1 4]
 [2 5 9]]


### tf.transpose 提供了矩阵转置功能
将a进行转置，并且根据perm参数(指的是轴的序号)重新排列输出维度。这是对数据的维度的进行操作的形式。

In [40]:
x = tf.constant([[[1,2,3],
                 [4,5,6]],
                [[7,8,9],
                [10, 11, 12]]])
a = tf.transpose(x, perm = [0,2,1])
print(a.numpy())
print(x.shape)
print(a.shape)

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]
(2, 2, 3)
(2, 3, 2)


### tf.math.argmax 提供返回数组内最大值对应的 索引

In [41]:
a = tf.constant([1,2,3,4,5])
x = tf.math.argmax(a)
x.numpy()

4

### tf.expand_dims 在输入的Tensor中增加一个维度
其中axis配置需要添加维度的下标

In [42]:
a = tf.constant([[1], [2], [3]])
print(a.shape)

b = tf.expand_dims(a, 0)
print(b.shape)
print(b)

(3, 1)
(1, 3, 1)
tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)


### tf.concat的作用是将多个Tensor在同一个维度建立连接

In [43]:
a1 = tf.constant([[2,3,4], [4,5,6], [2,3,4]])
a2 = tf.constant([[1,2,2], [6,7,8], [2,3,2]])

b = tf.concat([a1, a2], axis = 0)
b.numpy()

array([[2, 3, 4],
       [4, 5, 6],
       [2, 3, 4],
       [1, 2, 2],
       [6, 7, 8],
       [2, 3, 2]], dtype=int32)

### tf.bitcast提供了数据类型转换功能
input需要转换的Tensor，type为转换后的类型

In [44]:
a = tf.constant(32.0)
b = tf.bitcast(a, type = tf.int32)

print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


## TF的高阶API（tf.keras）

### 搭建神经网络模型

In [45]:
import tensorflow as tf
import numpy as np

In [47]:
# 实例化一个 tf.keras.Sequential
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(input_dim = 1, units = 1)) # 输入输出维度

model.compile(loss = 'mse', optimizer = 'sgd')

### 训练神经网络模型

In [62]:
X = np.linspace(-10, 10, 700)
Y = 2*X + 100 + np.random.normal(0, 0.1, (700,))

# begin training
model.fit(X, Y, verbose=1, epochs = 500, validation_split = 0.2) # verbose：日志显示，0为不在标准输出流输出日志信息，1为输出进度条记录，2为每个epoch输出一行记录



Train on 560 samples, validate on 140 samples
Epoch 1/500
560/560 [==============================] - 0s 147us/sample - loss: 207.1857 - val_loss: 490.9057
Epoch 2/500
560/560 [==============================] - 0s 51us/sample - loss: 111.2488 - val_loss: 214.2681
Epoch 3/500
560/560 [==============================] - 0s 66us/sample - loss: 60.0021 - val_loss: 146.3414
Epoch 4/500
560/560 [==============================] - 0s 70us/sample - loss: 32.7615 - val_loss: 87.6950
Epoch 5/500
560/560 [==============================] - 0s 81us/sample - loss: 17.9124 - val_loss: 41.5931
Epoch 6/500
560/560 [==============================] - 0s 52us/sample - loss: 9.7095 - val_loss: 23.5664
Epoch 7/500
560/560 [==============================] - 0s 59us/sample - loss: 5.2712 - val_loss: 12.5855
Epoch 8/500
560/560 [==============================] - 0s 56us/sample - loss: 2.8978 - val_loss: 7.2804
Epoch 9/500
560/560 [==============================] - 0s 55us/sample - loss: 1.5753 - val_loss: 3.4860


560/560 [==============================] - 0s 48us/sample - loss: 0.0103 - val_loss: 0.0086
Epoch 156/500
560/560 [==============================] - 0s 49us/sample - loss: 0.0102 - val_loss: 0.0086
Epoch 157/500
560/560 [==============================] - 0s 48us/sample - loss: 0.0102 - val_loss: 0.0093
Epoch 158/500
560/560 [==============================] - 0s 45us/sample - loss: 0.0102 - val_loss: 0.0084
Epoch 159/500
560/560 [==============================] - 0s 50us/sample - loss: 0.0104 - val_loss: 0.0086
Epoch 160/500
560/560 [==============================] - 0s 49us/sample - loss: 0.0102 - val_loss: 0.0085
Epoch 161/500
560/560 [==============================] - 0s 47us/sample - loss: 0.0102 - val_loss: 0.0084
Epoch 162/500
560/560 [==============================] - 0s 46us/sample - loss: 0.0101 - val_loss: 0.0088
Epoch 163/500
560/560 [==============================] - 0s 48us/sample - loss: 0.0102 - val_loss: 0.0086
Epoch 164/500
560/560 [==============================] - 0s 

560/560 [==============================] - 0s 50us/sample - loss: 0.0101 - val_loss: 0.0084
Epoch 310/500
560/560 [==============================] - 0s 48us/sample - loss: 0.0102 - val_loss: 0.0086
Epoch 311/500
560/560 [==============================] - 0s 47us/sample - loss: 0.0103 - val_loss: 0.0122
Epoch 312/500
560/560 [==============================] - 0s 46us/sample - loss: 0.0102 - val_loss: 0.0084
Epoch 313/500
560/560 [==============================] - 0s 47us/sample - loss: 0.0102 - val_loss: 0.0101
Epoch 314/500
560/560 [==============================] - 0s 45us/sample - loss: 0.0102 - val_loss: 0.0086
Epoch 315/500
560/560 [==============================] - 0s 48us/sample - loss: 0.0102 - val_loss: 0.0086
Epoch 316/500
560/560 [==============================] - 0s 48us/sample - loss: 0.0101 - val_loss: 0.0091
Epoch 317/500
560/560 [==============================] - 0s 45us/sample - loss: 0.0102 - val_loss: 0.0094
Epoch 318/500
560/560 [==============================] - 0s 

560/560 [==============================] - 0s 49us/sample - loss: 0.0102 - val_loss: 0.0096
Epoch 464/500
560/560 [==============================] - 0s 50us/sample - loss: 0.0102 - val_loss: 0.0089
Epoch 465/500
560/560 [==============================] - 0s 50us/sample - loss: 0.0101 - val_loss: 0.0084
Epoch 466/500
560/560 [==============================] - 0s 49us/sample - loss: 0.0102 - val_loss: 0.0084
Epoch 467/500
560/560 [==============================] - 0s 49us/sample - loss: 0.0102 - val_loss: 0.0099
Epoch 468/500
560/560 [==============================] - 0s 48us/sample - loss: 0.0102 - val_loss: 0.0085
Epoch 469/500
560/560 [==============================] - 0s 49us/sample - loss: 0.0102 - val_loss: 0.0086
Epoch 470/500
560/560 [==============================] - 0s 48us/sample - loss: 0.0102 - val_loss: 0.0084
Epoch 471/500
560/560 [==============================] - 0s 49us/sample - loss: 0.0102 - val_loss: 0.0090
Epoch 472/500
560/560 [==============================] - 0s 

### 保存神经网络模型

In [63]:
filename = 'line_model.h5'
model.save(filename)
print('model save as line_model.h5')

model save as line_model.h5


In [64]:
x = tf.constant([0.5])
model = tf.keras.models.load_model(filename)
y = model.predict(x)
y_correct = x.numpy() * 2 + 100 + np.random.normal(0, 0.1, (1,))

print(y,y_correct)

[[100.99767]] [100.98229333]
